//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarSystem.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Order> C_Order { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<OrderProduct> OrderProducts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    
        public virtual ObjectResult<SP_Order_Result> SP_Order()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Order_Result>("SP_Order");
        }
    
        public virtual ObjectResult<SP_Order_Result> SP_Order_By_OwerId(string owerId)
        {
            var owerIdParameter = owerId != null ?
                new ObjectParameter("OwerId", owerId) :
                new ObjectParameter("OwerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Order_Result>("SP_Order_By_OwerId", owerIdParameter);
        }
    
        public virtual ObjectResult<SP_OrderProducts_Result> SP_OrderProducts_By_OrderId(Nullable<int> orderId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OrderProducts_Result>("SP_OrderProducts_By_OrderId", orderIdParameter);
        }
    
        public virtual ObjectResult<SP_Product_Result> SP_Product()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Product_Result>("SP_Product");
        }
    }
}
